
% tt=ti;
tt=comed;
ttlim=100;
otherlim=150;
h1=figure('Name','cell axis angle');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ca1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ca2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ca3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: C');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ca4,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: D');
suptitle('cell axis angle');

h2=figure('Name','cell aspect ratio');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,car1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,car2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,car3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: C');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,car4,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: D');
suptitle('cell aspect ratio');

h3=figure('Name','cell energy');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceE1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceE2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceE3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: C');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceE4,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: D');
suptitle('cell energy');

h4=figure('Name','pair and total energy');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cE13,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A and C');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cE24,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B and D');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cE1234,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A, B, C and D');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cEE,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('All cells');
suptitle('total cell energy');

h5=figure('Name','others');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ca1234,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('total axis angle');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,car1234,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('total aspect ratio');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,edlsurr,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('length of edge surrounding Perimeters');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceisoqu_1234,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('length of total isoqu');

h6=figure('Name','cell U1');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU1_1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU1_2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU1_3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: C');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU1_4,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: D');
suptitle('cell U1');

h7=figure('Name','pair and total U1');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU1_13,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A and C');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU1_24,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B and D');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU1_1234,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A, B, C and D');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cUU1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('All cells');
suptitle('total cell U1');

h8=figure('Name','cell U2');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU2_1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU2_2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU2_3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: C');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU2_4,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: D');
suptitle('cell U2');

h9=figure('Name','pair and total U2');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU2_13,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A and C');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU2_24,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B and D');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU2_1234,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A, B, C and D');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cUU2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('All cells');
suptitle('total cell U2');

h10=figure('Name','cell U3');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU3_1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU3_2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU3_3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: C');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceU3_4,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: D');
suptitle('cell U3');

h11=figure('Name','pair and total U3');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU3_13,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A and C');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU3_24,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B and D');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cU3_1234,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A, B, C and D');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cUU3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('All cells');
suptitle('total cell U3');

h12=figure('Name','cell Areas');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceAA_1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceAA_2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceAA_3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: C');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceAA_4,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: D');
suptitle('cell Areas');

h13=figure('Name','pair and total Areas');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cAA_13,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A and C');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cAA_24,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B and D');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,cAA_1234,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A, B, C and D');
suptitle('total cell Areas');

h14=figure('Name','cell isoqus');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceisoqu_1,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: A');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceisoqu_2,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: B');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceisoqu_3,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: C');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,ceisoqu_4,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('cell: D');
suptitle('cell isoqus');

h15=figure('Name','length of neighbor edges');
subplot(2,2,1);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,edlabad,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('length of edge AB+AD');
subplot(2,2,2);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,edlcdcb,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('length of edge CB+CD');
subplot(2,2,3);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,edlabcd,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('length of edge AB+BC+CD+DA');
subplot(2,2,4);
[ xaxi,yaxi,out,~ ] = gethist( tt,ttlim,edlabcde,otherlim );
surf(xaxi,yaxi,out');
shading interp;
title('length of edge AB+BC+CD+DA+common_edge');
suptitle('length of neighbor edges');

saveas(h1,[foldername,'/ph_ca.fig']);
saveas(h2,[foldername,'/ph_car.fig']);
saveas(h3,[foldername,'/ph_ceEa.fig']);
saveas(h4,[foldername,'/ph_ceEb.fig']);
saveas(h5,[foldername,'/ph_others.fig']);
saveas(h6,[foldername,'/ph_ceU1a.fig']);
saveas(h7,[foldername,'/ph_ceU1b.fig']);
saveas(h8,[foldername,'/ph_ceU2a.fig']);
saveas(h9,[foldername,'/ph_ceU2b.fig']);
saveas(h10,[foldername,'/ph_ceU3a.fig']);
saveas(h11,[foldername,'/ph_ceU3b.fig']);
saveas(h12,[foldername,'/ph_ceAAa.fig']);
saveas(h13,[foldername,'/ph_ceAAb.fig']);
saveas(h14,[foldername,'/ph_ceisoqu.fig']);
saveas(h15,[foldername,'/ph_lengthofedgesconnected.fig']);
close(h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13,h14,h15);
% suptitle('cell1~cell4 are represented by red,green,blue,magenta');


% figure;
% plot(tt,comed);
% plot(comed,cEE);
